// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Nr2f6R0UuSnFHkw8Bp_DXvEPV4lv4BQ',
    appId: '1:91490255864:web:3a4b46f1b96bf3d7720c0d',
    messagingSenderId: '91490255864',
    projectId: 'parkit-889df',
    authDomain: 'parkit-889df.firebaseapp.com',
    storageBucket: 'parkit-889df.appspot.com',
    measurementId: 'G-HBX9VXYQEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC9wzQ3osAuXa71fAsPsVAfFSyyYOcC2g',
    appId: '1:91490255864:android:de946befa95c1e35720c0d',
    messagingSenderId: '91490255864',
    projectId: 'parkit-889df',
    storageBucket: 'parkit-889df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKyfn60JFscMjSTIIk-PJQjH6bgzgkR0g',
    appId: '1:91490255864:ios:be51f8b92d4757f4720c0d',
    messagingSenderId: '91490255864',
    projectId: 'parkit-889df',
    storageBucket: 'parkit-889df.appspot.com',
    iosBundleId: 'com.example.parkit',
  );
}
